Added command cooldowns.
BPEssentials/Core pull request #91
Opened 2020-09-24 02:02 UTC by ggggg

2020-10-11 15:42 UTC, PLASMAchicken requested changes

2020-10-11 15:42 UTC, PLASMAchicken commented on src/BPEssentials/Core.cs
>                          }
Huh?

2020-10-11 15:42 UTC, PLASMAchicken commented on src/BPEssentials/Core.cs
> +                        if (!player.GetExtendedPlayer().EnabledBypass)
```suggestion
                        if (player.GetExtendedPlayer().EnabledBypass)
                        {
                        return true;
                        }
```

2020-10-11 15:42 UTC, PLASMAchicken commented on src/BPEssentials/Core.cs
> +                    out var instance))
Huh?

2020-10-11 15:42 UTC, PLASMAchicken commented on src/BPEssentials/Core.cs
> +                                //TODO localtion
Huh?

2020-10-11 21:29 UTC, ggggg commented on src/BPEssentials/Core.cs
> +                    out var instance))
What was even changed (but formating)?

2020-10-11 21:32 UTC, PLASMAchicken commented on src/BPEssentials/Core.cs
> +                    out var instance))
Nothing but formatting wich is bad

2020-10-11 21:34 UTC, ggggg commented on src/BPEssentials/Core.cs
> +                                //TODO localtion
wdym

2020-10-13 18:22 UTC, ggggg commented on src/BPEssentials/Core.cs
> +                    out var instance))
how so

2020-10-14 11:28 UTC, PLASMAchicken commented on src/BPEssentials/Core.cs
> +                    out var instance))
This linebreak is ugly

2020-10-14 11:28 UTC, PLASMAchicken commented on src/BPEssentials/Core.cs
> +                                //TODO localtion
Todo comment ?!

2020-10-17 01:38 UTC, PLASMAchicken requested changes
.

2020-11-21 00:53 UTC, ggggg commented on src/BPEssentials/Core.cs
> +                                //TODO localtion
ah

2021-07-15 19:08 UTC, ggggg commented on src/BPEssentials/Core.cs
>                          }
What?

2021-11-16 23:33 UTC, PLASMAchicken commented
Failed to fix Suggested Changes and PR is stale.

2021-11-16 23:33 UTC, closed without merging